### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by jeffreybarry** [jeffreybarry/alephBlog#1]
Modify the existing Aleph theme, which itself is a modification of Underscores with Bootstrap.
(Writing out the steps is a good way to structure work tasks.)

- [x] blog menu option set to active

- [ ] set footer options

- [x] remove newsletter subscribe box

- [x] import blog content

- [x] set archives menu link

- [x] set masthead menu link

- [x] set submit menu link

- [x] set donate menu link
